### PR TITLE
Support multi-element GOPATH

### PR DESCRIPTION
**Pull request by jhillyerd**
- Use build.Package.Dir to find package source
- Use build.Package.SrcRoot find package source root directory
- Add build output to .gitignore

### CODE REVIEW

**Comment by jhillyerd** [comment]
I wrote some code to parse GOPATH and iterate over in an attempt to locate each package.  While messing with my GOPATH to make it fail, I found that `pkg, err := build.Default.Import(dep, "", build.FindOnly)` was blowing up before my code was even executed.  Turns out Go already computes everything homebrew-go-resources needed.

**Comment by samertm** [comment]
Looks good to me! I assume you tested this?

**Comment by jhillyerd** [comment]
Yes, used it with a two element GOPATH successfully. I tested packages in both elements. Go 1.6 on El Capitan.

**Comment by samertm** [comment]
Thanks for the PR!

**Pull request merged**
